import { GenerateView, IgnoreViewModel } from "../../../..";
import { DoctorEvil } from "./doctoEvil";

@GenerateView({
    model: "SubDoctorEvilViewModel",
    type: 'class',
    filePath: "./test/dist/_autogenerated_viewmodels/evils",
    mapperPath: "./test/dist/_autogenerated_viewmodels/evils/mappers"})
export class SubDoctorEvil extends DoctorEvil {
    height?: number;
}