import {GenerateView, IgnoreDecorators, IgnoreViewModel, ViewModelName, ViewModelType} from "../../../../src/index";
import {HeroDetail} from "./heroDetail";
import { notAsyncTransformer, asyncTransformer } from "../../../../transformer/asyncTransformer";
import { Length, ValidateIf, MaxLength, Max } from "class-validator";
import {NotExistiningDecoratorForClass} from 'node-modules-library';

@GenerateView({
    model: "ContextHeroModel",
    type: 'class',
    filePath: "./test/dist/_autogenerated_viewmodels/heroes",
    mapperPath: "./test/dist/_autogenerated_viewmodels/heroes/mappers"})
@NotExistiningDecoratorForClass()
export class Hero {
    @IgnoreViewModel("ContextHeroModel")
    public id?: number;

    @Max(1000)
    @Length(0,20)
    @ValidateIf(o => o.otherProperty === 'value')
    @ValidateIf(o => o.toty !== "value")
    public name: string;

    @ViewModelName("detailForView", "ContextHeroModel")
    @ViewModelType({
    modelName: "ContextHeroModel",
    nullable: false,
    transformer: { 
        toView: { function: asyncTransformer},
        fromView: { function: null }
    },
    type: HeroDetail})
    @IgnoreDecorators()
    @ValidateIf(o => o.toty !== "value")
    public detail: HeroDetail;
}
