import {GenerateView, IgnoreDecorators, IgnoreViewModel, ViewModelName, ViewModelType} from "../../../../src/index";
import {HeroDetail} from "./heroDetail";
import { notAsyncTransformer, asyncTransformer } from "../../../../transformer/asyncTransformer";
import { Length } from "class-validator";

@GenerateView({
    model: "ContextHeroModel",
    type: 'class',
    filePath: "./test/dist/_autogenerated_viewmodels/heroes",
    mapperPath: "./test/dist/_autogenerated_viewmodels/heroes/mappers"})
export class Hero {
    @IgnoreViewModel("ContextHeroModel")
    public id?: number;

    @Length(0,20)
    public name: string;

    @ViewModelName("detailForView", "ContextHeroModel")
    @ViewModelType({
    modelName: "ContextHeroModel",
    nullable: false,
    transformer: { 
        toView: { function: asyncTransformer},
        fromView: { function: null }
    },
    type: HeroDetail})
    @IgnoreDecorators()
    public detail: HeroDetail;
}
