import {GenerateView, IgnoreViewModel, ViewModelName, ViewModelType, NeedMapper} from "../../../../src/index";

@GenerateView({"modelName": "./test/dist/_autogenerated_viewmodels/heroes/heroDetailViewModel.ts",
    "mapperPath": "./test/dist/_autogenerated_viewmodels/heroes/mappers"})
@NeedMapper()
export class HeroDetail {

    @IgnoreViewModel()
    public id?: number;

    @ViewModelName("detail")
    public data: string;
}