import { GenerateView, IgnoreViewModel, ViewModelName } from '../../../../src/index';

@GenerateView({
    model: 'SimpeHeroViewModel',
    filePath: './test/dist/_autogenerated_viewmodels/heroes',
    mapperPath: './test/dist/_autogenerated_viewmodels/heroes/mappers' })
export class SimpleHero {
  @ViewModelName('login')
  public name: string;

  public age: string;

  @IgnoreViewModel()
  public nation: string;

  public proffesion: string;

  public level: number;

  public siblings: string[];

}
