import {GenerateView, IgnoreViewModel, ViewModelName, ViewModelType} from "../../../../src/index";

@GenerateView({"modelName": "./test/dist/_autogenerated_viewmodels/heroes/simpleHeroViewModel.ts",
    "mapperPath": "./test/dist/_autogenerated_viewmodels/heroes/mappers"})
export class SimpleHero {
  @ViewModelName("login")
  public name: string;

  public age: string;

  @IgnoreViewModel()
  public nation: string;

  public proffesion: string;

  public level: number;

  public siblings: string[];

}
