"use strict";

import * as fs from "fs";
import {} from "mocha";
import {createViewModels} from "../../../src/index";
import {Options, FileMapping} from "../../../src/tasks/model/options";
import {expect} from "chai";


describe("E2E Tests", () => {

      it("Hero", (done) => {
console.log(process.cwd());
        let expectedFileName = "./test/src/expected/hero/heroViewModel.ts",
            generatedFileName = "./test/dist/_autogenerated_viewmodels/heroes/heroViewModel.ts",
            sourceFileName = "./test/src/model/hero/hero.ts";

        let options: Options = {
          files: [
            {
              viewModelNames: [ "HeroViewModel"],
              source: sourceFileName,
              destination: generatedFileName
            },
            {
              viewModelNames: [ "HeroViewModel1"],
              source: sourceFileName,
              destination: "./test/dist/_autogenerated_viewmodels/heroes/heroViewModel1.ts"
            },
            {
              viewModelNames: ["HeroDetailViewModel"],
              source:  "./test/src/model/hero/heroDetail.ts",
              destination: "./test/dist/_autogenerated_viewmodels/heroes/heroDetailViewModel.ts"
            }
          ],
          allInOneFile: null,
        };

        createViewModels(options);
        let expected = fs.readFileSync(expectedFileName, "utf-8");
        let result = fs.readFileSync(generatedFileName, "utf-8");

        let expected2 = fs.readFileSync("./test/src/expected/hero/heroViewModel.ts", "utf-8");
        let result2 = fs.readFileSync( "./test/dist/_autogenerated_viewmodels/heroes/heroViewModel1.ts", "utf-8");

        done();
        expect(result).be.equal(expected);
        expect(result2).be.equal(expected2);

        done();
      });

});
